### using Postman to test the API

############################################
###### Localhost port 3000 ######

### Orders ###
# get all the orders
GET http://localhost:3000/orders

# get a specific order
# ex: 65f1a1b1e214b12345680004
GET http://localhost:3000/orders/67516b816506fe63d93a6fc3

# create a new order
POST http://localhost:3000/orders
{
    "customerId": "65f1a1b1e214b12345678912" ,
    "date": "2024-12-12",
    "total": 24.99,
    "bookId": "65f1a1b1e214b12345679004",
    "status": "Pending"
}

# update a specific order
# ex: orderId 67516b226506fe63d93a6fc2
PUT http://localhost:3000/orders/67516b226506fe63d93a6fc2
{
    "customerId": "65f1a1b1e214b12345678903" ,
    "date": "2024-03-03",
    "total": 21.99,
    "bookId": "65f1a1b1e214b12345679003",
    "status": "Shipped"
}

# delete a specific order
# ex: id
DELETE http://localhost:3000/orders/67516b816506fe63d93a6fc3

############################################
###### Render ######

### Orders ###